behaviors:
  #Training Mode = 2
  #School_From2F
  2F_B_StairSide:
    trainer_type: ppo

    max_steps: 2000000
    keep_checkpoints: 200
    checkpoint_interval: 100000
    time_horizon: 96
    summary_freq: 10000
    threaded: true

    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 1e-4
      beta: 1e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

      curiosity:
        gamma: 0.995
        strength: 0.05
        encoding_size: 64
        learning_rate: 3e-4
  

  2F_A_StairSide:
    trainer_type: ppo

    max_steps: 10000000
    keep_checkpoints: 200
    checkpoint_interval: 100000
    time_horizon: 96
    summary_freq: 10000
    threaded: true

    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 1e-4
      beta: 1e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

      curiosity:
        gamma: 0.995
        strength: 0.05
        encoding_size: 64
        learning_rate: 3e-4


  2F_C_StairSide:
    trainer_type: ppo

    max_steps: 10000000
    keep_checkpoints: 200
    checkpoint_interval: 100000
    time_horizon: 96
    summary_freq: 10000
    threaded: true

    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 1e-4
      beta: 1e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

      curiosity:
        gamma: 0.995
        strength: 0.05
        encoding_size: 64
        learning_rate: 3e-4
  

    1F_B_StairSide:
    trainer_type: ppo

    max_steps: 2000000
    keep_checkpoints: 200
    checkpoint_interval: 100000
    time_horizon: 96
    summary_freq: 10000
    threaded: true

    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 1e-4
      beta: 1e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

      curiosity:
        gamma: 0.995
        strength: 0.05
        encoding_size: 64
        learning_rate: 3e-4
  

  1F_A_StairSide:
    trainer_type: ppo

    max_steps: 10000000
    keep_checkpoints: 200
    checkpoint_interval: 100000
    time_horizon: 96
    summary_freq: 10000
    threaded: true

    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 1e-4
      beta: 1e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

      curiosity:
        gamma: 0.995
        strength: 0.05
        encoding_size: 64
        learning_rate: 3e-4


  1F_C_StairSide:
    trainer_type: ppo

    max_steps: 10000000
    keep_checkpoints: 200
    checkpoint_interval: 100000
    time_horizon: 96
    summary_freq: 10000
    threaded: true

    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 1e-4
      beta: 1e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

      curiosity:
        gamma: 0.995
        strength: 0.05
        encoding_size: 64
        learning_rate: 3e-4


environment_parameters:
  SpawnableAreaNum:
    curriculum:
      - name: 2F_B_StairSide
        completion_criteria:
          measure: reward
          behavior: 2F_B_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 20.0

      - name: 2F_A_StairSide
        completion_criteria:
          measure: reward
          behavior: 2F_A_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 21.0

      - name: 2F_C_StairSide
        completion_criteria:
          measure: reward
          behavior: 2F_C_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 22.0

      - name: 1F_B_StairSide
        completion_criteria:
          measure: reward
          behavior: 1F_B_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 10.0

      - name: 1F_A_StairSide
        completion_criteria:
          measure: reward
          behavior: 1F_A_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 11.0

      - name: 1F_C_StairSide
        completion_criteria:
          measure: reward
          behavior: 1F_C_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 12.0

        - name: All
          value: 30.0


  StepReward:
    curriculum:
      - name: 2F_B_StairSide
        completion_criteria:
          measure: reward
          behavior: 2F_B_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: -0.0002

      - name: 2F_A_StairSide
        completion_criteria:
          measure: reward
          behavior: 2F_A_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: -0.0002

      - name: 2F_C_StairSide
        completion_criteria:
          measure: reward
          behavior: 2F_C_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: -0.0002

      - name: 1F_B_StairSide
        completion_criteria:
          measure: reward
          behavior: 1F_B_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: -0.0002

      - name: 1F_A_StairSide
        completion_criteria:
          measure: reward
          behavior: 1F_A_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: -0.0002

      - name: 1F_C_StairSide
        completion_criteria:
          measure: reward
          behavior: 1F_C_StairSide
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: -0.0002

        - name: All
          value: -0.00025